### ISSUE TITLE
Transparent window maximized

### ISSUE THREAD

**Issue by Polsulpicien** [yjg30737/pyqt-frameless-window#10]
Hello,

creating a transparent background window (`setStyleSheet("background: transparent")`) works fine but when you try to maximize this window (`setWindowState(Qt.WindowMaximized)`) the window isn't transparent anymore.
You don't get this issue when using `QMainWindow`.
Currently you can have a maximized window using `setGeometry(screen.x(), screen.y(), screen.width(), screen.height())`, but it would be nice to have the maximized function :D

*Note: I'm using the latest version (commit [#3228fc1](https://github.com/yjg30737/pyqt-frameless-window/commit/3228fc1a6a678e6b1491e1234655b42e6aeba955))*

Have a nice day, 
Thanks 👍🏼

**Comment by yjg30737** [comment]
Hello :)

I have updated to fix the AttributeError bug(which is really shameful and unexcuseable bug because of lack of test 😥), so it can be different now.

Can i see your code?

**Comment by Polsulpicien** [comment]
Umm it seems like the issue is related to `QtWin.enableBlurBehindWindow(self)`, because when I comment this line it works fine. And by the way I'm not able to drag the window, I get this error:
```py
File "pyqt_frameless_window\windows\baseWidget.py", line 54, in mousePressEvent
    if self._pressToMove:
AttributeError: 'BaseWidget' object has no attribute '_pressToMove'. Did you mean: 'isPressToMove'?
```

**Comment by yjg30737** [comment]
Yes. That's the AttributeError i've talked about.

If you clone or install the latest version of the package (v0.0.84) it should be work well

**Comment by Polsulpicien** [comment]
Yeah it's working now, thank you 👍🏼

**Comment by yjg30737** [comment]
you're welcome
