### ISSUE TITLE
Version 0.0.84 missing move event for Windows

### ISSUE THREAD

**Issue by MartinRapcan** [yjg30737/pyqt-frameless-window#12]
In BaseWidget for windows(dont know about others) using 0.0.80 in init there is defined self._pressToMove = True ... but in newer version 0.0.84 there is not defined self._pressToMove = True .. its moved into some _initSomething function .. that is not called .. that variable is not defined .. so there is no way to move window .. error only shows when closing app .. so I had to switch back to older version where it is defined

**Comment by yjg30737** [comment]
I've checked that out and i find out that _pressToMove is defined in _initVal() function in baseWidget.py in windows folder.

I tested in Python 3.10, 3.11 in Windows 11 with both PyQt5 and PySide6 and moving feature works.

I've cloned it to test and imported it from pypi to test as well. It is "main" branch.

![image](https://user-images.githubusercontent.com/55078043/228990159-4b26880b-ea2e-433d-af81-c2a340bc526b.png)

If you use pip, can you add the option "--upgrade"? I didn't know which version is that but i remember that i had actually removed the _pressToMove once. But i brought it back in 0.0.83 or something. So if you have the 0.0.81 or 0.0.82, it might not work. "--upgrade" option can override that version.

**Comment by MartinRapcan** [comment]
Well I installed version 0.0.84 back, and same thing happens 
![image](https://user-images.githubusercontent.com/71701657/229244780-68daf734-9205-423e-88e8-15bb45353cc9.png)

This is how I create my MainWindow
![image](https://user-images.githubusercontent.com/71701657/229244831-7cdd1f4c-255a-4179-947e-bc8c62f04fbf.png)

I got the correct version I was previosly refering to ..
![image](https://user-images.githubusercontent.com/71701657/229244875-82050782-4c50-4a49-8f3c-facc6dd78e8b.png)
same function ... yet same error .. is that function even call anywhere ? .. if I manually call that function in __init__ it will work like it suppose to .. or am I doing something wrong ?

**Comment by yjg30737** [comment]
Sorry for my belated reply 😥

That was totally my fault, it should've been QWidget instead of BaseWidget. I don't even know what i was thinking back then

```python
class FramelessMainWindow(QMainWindow, BaseWidget):
    changedToDark = Signal(bool)
    def __init__(self, hint=None, flags: list = []):
        super().__init__()
        self._initVal()
        self._initUi(hint, flags)

    def _initUi(self, hint, flags):
        super()._initUi(hint, flags)
        lay = QVBoxLayout()
        lay.addWidget(self._titleBar)
        lay.setContentsMargins(0, 0, 0, 0)
        lay.setSpacing(0)

        mainWidget = BaseWidget() # this is supposed to be QWidget
        mainWidget.setLayout(lay)

        self.setCentralWidget(mainWidget)
```

new BaseWidget which don't even initialize the necessary variable duplicates the parent window's feature, so that's why it causes the error. I didn't test it hard enough.

It works fine now.

It is v0.0.85 and i will upload it to pypi 12 hrs later.

**Comment by MartinRapcan** [comment]
No problem, glad it will be fixed. So we can close this issue then.
